### ISSUE TITLE
Use newer version of zeek

### ISSUE THREAD

**Issue by rsagy** [tenzir/dockerized-zeek#14]
I try to build a newer version of zeek: 5.1.0 using your docker build and received the following error:
Unpacking spicy (2.4.8) ...
dpkg-deb: error: 'zeek-btest_5.1.0-0_amd64.deb' is not a Debian format archive
dpkg: error processing archive zeek-btest_5.1.0-0_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2

Any idea how to solve it?
BTW: where can I find all the versions I can use with your docker buil?

Thanks in advance

**Comment by tobim** [comment]
I opened #15 to be able to build images with Zeek 5. It would be a great help if you could check if it works for you.

**Comment by tobim** [comment]
#15 was merged in the meantime. The images now contain Zeek 5.x.
